-- ========================================
-- JEPOY'S JBL PARTYBOX
-- BOOKING DATABASE
-- ========================================

create table if not exists public.bookings (

  id bigint generated by default as identity primary key,

  created_at timestamptz
    not null
    default now(),

  name text
    not null,

  phone text
    not null,

  package text
    not null,

  date date
    not null,

  address text
    not null,

  distance text,

  delivery_fee text,

  lat double precision,

  lng double precision,

  maps_link text,

  status text
    not null
    default 'pending'

);


-- ========================================
-- ENABLE SECURITY
-- ========================================

alter table public.bookings
enable row level security;


-- ========================================
-- ALLOW CUSTOMERS TO SEND BOOKINGS
-- ========================================

create policy "public can create booking"

on public.bookings

for insert

to anon, authenticated

with check (true);


-- ========================================
-- OWNER CAN VIEW BOOKINGS
-- ========================================

create policy "authenticated users can view bookings"

on public.bookings

for select

to authenticated

using (
  auth.uid() is not null
);


-- ========================================
-- OWNER CAN UPDATE BOOKINGS
-- ========================================

create policy "authenticated users can update bookings"

on public.bookings

for update

to authenticated

using (
  auth.uid() is not null
)

with check (
  auth.uid() is not null
);
